package org.trackitall.trackitall.enums;

public enum UserRole {
    ADMIN,
    GESTIONNAIRE_APROVISIONNEMENT,
    SUPERVISEUR_LOGISTIQUE,
    RESPONSABLE_ACHATS,
    CHEF_PRODUCTION,
    SUPERVISEUR_PRODUCTION,
    PLANIFICATEUR,
    SUPERVISEUR_COMMERCIAL,
    SUPERVISEUR_LIVRAISONS
}
